import { getSession } from "next-auth/client"
import Head from "next/head"
import Feed from "../components/body/feeds/Feed"
import SideBar from "../components/body/sidebar/SideBar"
import Widgets from "../components/body/widgets/Widgets"
import Header from "../components/header/Header"
import Login from "../components/Login"
import { db } from "../firebase"
export default function Home({ session, posts }) {
  if (!session) return <Login />

  return (
    <div className='overflow-hidden h-screen bg-gray-100'>
      <Head>
        <title>Facebook 2.0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Header */}
      <Header />
      <main className='flex'>
        {/* sidebar */}
        <SideBar />
        {/* Feed */}
        <Feed posts={posts} />
        {/* widgets */}
        <Widgets />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get()

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }))

  return {
    props: {
      session,
      posts: docs,
    },
  }
}
